### ISSUE TITLE
Summary missing for the event ErrorsChanged in Logic/Logic.Wpf/BaseDataModel.cs

### ISSUE THREAD

**Issue by devdeer-mahmoud** [devdeer/DoctorFlox#16]
Hello,
there is a missing summary for the event ErrorsChanged in [BaseDataModel.cs](https://github.com/devdeer/DoctorFlox/blob/master/src/Logic/Logic.Wpf/BaseDataModel.cs)

`/// <inheritdoc />`
`public event EventHandler<DataErrorsChangedEventArgs> ErrorsChanged;`

and

`/// <inheritdoc />`
`public IEnumerable GetErrors(string propertyName)`

Best regards

**Comment by devdeer-alex** [comment]
We will fix this with the next commit. Thx!

**Comment by devdeer-alex** [comment]
The event and the method are defined in `INotifyDataErrorInfo` and thus the `inheritdoc` is correct.

**Comment by devdeer-mahmoud** [comment]
Thx, you are right I found it now.
