### ISSUE TITLE
The sample method should be named -Sample instead of -Test

### ISSUE THREAD

**Issue by devdeer-jens** [devdeer/DoctorFlox#57]
https://github.com/devdeer/DoctorFlox/blob/168bc0c18e6f5233d1c95579a98abf049649aed5/src/Ui/Ui.WpfSample/ViewModels/MainViewModel.cs#L154

By naming the method "RunAsyncMessenger**Sample**" it would state clearly that its a sample method and has nothing to do with the tests of the project.

**Comment by devdeer-alex** [comment]
Not flagged as resolved but implemented.
